import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/Theme-provider";
import Header from "@/components/ui/Header";
import {ClerkProvider} from '@clerk/nextjs'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider >
    <html lang="en" suppressHydrationWarning className="dark">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  p-2  bg-black ` }
        
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* header */}
            <Header/>
            <main className="  p-2 min-h-screen">

            {children}
            </main>
            {/* footer */}
            <footer className=" bg-muted/60 py-12">
              <div className=" container mx-auto px-4 text-center text-gray-200">

              </div>
            </footer>





          </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
